CREATE EXTENSION IF NOT EXISTS vector;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'genero_enum'
    ) THEN
        CREATE TYPE genero_enum AS ENUM (
            'ROMANCE',
            'FANTASIA',
            'FICCAO',
            'TERROR',
            'SUSPENSE',
            'CIENCIA',
            'BIOGRAFIA',
            'CLASSICO',
            'INFANTIL',
            'POEMA'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS livros (
    id VARCHAR(20) PRIMARY KEY,
    titulo VARCHAR(255),
    autor VARCHAR(255),
    genero genero_enum,
    ano INT,
    numero_paginas INT,
    descricao TEXT,
    embedding VECTOR(384)
);

-- Para uma base pequena, a busca exata já é suficiente.
-- Em bases maiores, este índice acelera a distância por cosseno.
CREATE INDEX IF NOT EXISTS livros_embedding_hnsw_idx
ON livros USING hnsw (embedding vector_cosine_ops);

-- INSERTS

INSERT INTO livros VALUES ('L0001', 'É assim que começa', 'Colleen Hoover', 'ROMANCE', 2022, 336, '“Lily e o seu ex-marido, Ryle, acabaram de se adaptar numa situação de compartilhamento de guarda quando, de repente, ela se reencontra com seu primeiro amor, Atlas. Depois de quase dois anos separados, o tempo finalmente parece estar ao favor de ambos, e Lily imediatamente aceita o convite para um encontro.', NULL);
INSERT INTO livros VALUES ('L0004', 'O Universo Numa Casca de Noz', 'Stephen Hawking', 'CIENCIA', 2001, 223, 'Após o enorme sucesso de Uma breve história do tempo, a Intrínseca traz a luxuosa reedição de O universo numa casca de noz, na qual Stephen Hawking se vale de ilustrações, fotos e esquemas detalhados para mostrar grandes descobertas no campo da física teórica. Tudo isso, é claro, com sua conhecida clareza, elucidando temas complexos por meio de conceitos e ideias do dia a dia, como a inflação, as cartas de baralho e as linhas ferroviárias, e permeado com seu peculiar senso de humor.', NULL);
INSERT INTO livros VALUES ('L0015', 'O Senhor dos Anéis- A Sociedade do Anel', 'J.R.R. Tolkien', 'FANTASIA', 1954, 576, 'Numa cidadezinha indolente do Condado, um jovem hobbit é encarregado de uma imensa tarefa. Deve empreender uma perigosa viagem através da Terra-média até as Fendas da Perdição, e lá destruir o Anel do Poder - a única coisa que impede o domínio maléfico do Senhor do Escuro. A Sociedade do Anel é a primeira Temporada da grande obra de ficção fantástica de J. R. R. Tolkien, O Senhor dos Anéis.', NULL);
INSERT INTO livros VALUES ('L0016', 'Drácula', 'Bram Stoker', 'TERROR', 1897, 418, 'Drácula, um clássico que ainda corre quente na veia de inúmeras gerações de leitores por todo o mundo e a mais celebrada narrativa de vampiros, continua a transcender fronteiras de tempo, espaço, história e memória.', NULL);
INSERT INTO livros VALUES ('L0027', 'Percy Jackson e Os Olimpianos- ladrão de raios', 'Rick Riordan', 'FANTASIA', 2015, 331, 'Unindo mitologia grega, muita aventura e tramas hilárias, a história de Rick Riordan sobre um adolescente com TDAH que descobre ser filho do deus do mar e precisa navegar entre o mundo humano e o divino.', NULL);
INSERT INTO livros VALUES ('L0033', 'Grande Sertão Veredas', 'João Guimarães Rosa', 'ROMANCE', 1956, 560, 'Grande sertão: veredas é o livro mais famoso de Guimarães Rosa e conta a história de amor entre Riobaldo e Diadorim (ou Reinaldo). O ex-jagunço Riobaldo relata, para um interlocutor não nomeado na obra, fatos de sua juventude em meio a um bando de jagunços.', NULL);
INSERT INTO livros VALUES ('81258637', 'The Bastard Son & The Devil Himself', 'Colleen Hoover', 'FANTASIA', 2022, 368, 'Caught between two warring clans, the son of a notorious witch responsible for a deadly massacre tries to find his place in the world — and his powers.', NULL);
INSERT INTO livros VALUES ('L0002', 'A Hipótese do Amor', 'Ali Hazelwood', 'ROMANCE', 2022, 453, 'Olive Smith, aluna do doutorado em Biologia da Universidade Stanford, acredita na ciência – não em algo incontrolável como o amor.Depois de sair algumas vezes com Jeremy, ela percebe que sua melhor amiga gosta dele e decide juntá-los. Para mostrar que está feliz com essa escolha, Olive precisa ser convincente: afinal, cientistas exigem provas.Sem muitas opções, ela resolve inventar um namoro de mentira e, num momento de pânico, beija o primeiro homem que vê pela frente.O problema é que esse homem é Adam Carlsen, um jovem professor de prestígio – conhecido por levar os alunos às lágrimas. Por isso, Olive fica chocada quando o tirano dos laboratórios concorda em levar adiante a farsa e fingir ser seu namorado.De repente, seu pequeno experimento parece perigosamente próximo da combustão e aquela pequena possibilidade científica, que era apenas uma hipótese sobre o amor, transforma-se em algo totalmente inesperado.', NULL);
INSERT INTO livros VALUES ('L0003', 'Uma Breve História do Tempo', 'Stephen Hawking', 'CIENCIA', 1988, 256, 'Uma das mentes mais geniais do mundo moderno, Stephen Hawking guia o leitor na busca por respostas a algumas das maiores dúvidas da humanidade: Qual a origem do universo? Ele é infinito? E o tempo? Sempre existiu, ou houve um começo e haverá um fim? Existem outras dimensões além das três espaciais? E o que vai acontecer quando tudo terminar?', NULL);
INSERT INTO livros VALUES ('L0005', 'O Universo Elegante', 'Brian Greene', 'CIENCIA', 1999, 480, 'Tudo o que existe e acontece no mundo, no universo, surge das vibrações dessas entidades centenas de bilhões e bilhões de vezes menores do que o núcleo de um átomo. Hoje, no mundo inteiro, físicos e matemáticos trabalham febrilmente com a idéia de ''cordas''.', NULL);
INSERT INTO livros VALUES ('L0006', 'Breves Respostas para Grandes Questões', 'Stephen Hawking', 'CIENCIA', 2018, 256, 'Nessa obra inédita de um dos maiores gênios da física moderna, investigamos questões que encantam a humanidade desde os primórdios da sociedade até a atualidade, como a existência de Deus, de vida inteligente fora da Terra ou o início do universo.', NULL);
INSERT INTO livros VALUES ('L0007', 'O Homem de Giz', 'C. J. Tudor', 'SUSPENSE', 2018, 272, 'Em 2016, Eddie e seus amigos, já com certa idade, recebem uma carta com um desenho de um homem de giz enforcado. Ocorre, então, que um de seus amigos repentinamente aparece morto. Eddie não tem dúvidas de que precisa descobrir quem cometeu o crime e como isso se relaciona com o passado de 30 anos atrás.', NULL);
INSERT INTO livros VALUES ('L0008', 'Manual de Assassinato para Boas Garotas', 'Holly Jackson', 'SUSPENSE', 2022, 448, 'Na história, Pippa Fitz-Amobi está prestes a concluir o seu ensino médio e decide fazer o seu projeto de conclusão de curso sobre a investigação do caso Andie Bell: a garota mais bonita e popular da escola assassinada em 2012 por seu namorado, Sal Singh, que cometeu suicídio dias após o crime.', NULL);
INSERT INTO livros VALUES ('L0037', 'Vidas Secas', 'Graciliano Ramos', 'CLASSICO', 1938, 176, 'A história de uma família pobre da região seca do Nordeste e sua luta diária por trabalho e comida para sobreviver e superar as dificuldades do ambiente árido em que vive. Baseado no livro homônimo de Graciliano Ramos.', NULL);
INSERT INTO livros VALUES ('L0036', 'Gabriela Cravo e Canela', 'Jorge Amado', 'ROMANCE', 1958, 336, 'O romance é ambientado na Ilhéus dos anos 1920, uma cidade do interior baiano que passa por súbitas transformações graças à riqueza que a cultura do cacau está trazendo para a região. Tudo começa quando a cidade está em ebulição com a notícia de um duplo assassinato.', NULL);
INSERT INTO livros VALUES ('L0043', 'A divina Comédia', 'Dante Alighieri', 'POEMA', 1472, 696, 'O livro relata a viagem de Dante ao Inferno, ao Purgatório e ao Paraíso.', NULL);
INSERT INTO livros VALUES ('L0009', 'Anatomia do Mal', 'Harold Schechter', 'BIOGRAFIA', 2013, 480, 'O que faz gente aparentemente normal começar a matar e não parar mais? O que move - e o que pode deter - assassinos em série como Ed Gein, o psicopata americano que inspirou os mais célebres maníacos do cinema, como Norman Bates (Psicose), Leatherface (O Massacre da Serra Elétrica) e Hannibal Lecter (O Silêncio dos Inocentes). Como explicar a compulsão por matar e o prazer de causar dor, sem qualquer arrependimento? De onde vem tanta fúria? As respostas estão no novo lançamento da editora DarkSide Books: Serial Killers - Anatomia do Mal, dossiê definitivo sobre o universo sombrio dos psicopatas mais perversos da história.', NULL);
INSERT INTO livros VALUES ('L0010', 'Os Sertões', 'Euclides da Cunha', 'CLASSICO', 1902, 664, 'A obra trata da Guerra de Canudos que aconteceu no interior da Bahia. O autor, que era correspondente do jornal O Estado de São Paulo, presenciou Temporada dos acontecimentos na região e os descreveu de forma fiel. Além de desenvolver um romance histórico que mistura uma narrativa literária, sociológica e geográfica.', NULL);
INSERT INTO livros VALUES ('L0011', 'O Gato Malhado e a Andorinha Sinhá', 'Jorge Amado', 'INFANTIL', 1978, 128, 'Com grande lirismo, Jorge Amado narra a história do amor de um gato mau por uma adorável andorinha. Com ilustrações aquareladas do artista plástico Carybé, a narrativa mostra como duas criaturas bem diferentes podem não apenas conviver em paz como mudar a maneira que cada um tem de ver o mundo.', NULL);
INSERT INTO livros VALUES ('L0012', 'O Jardim das Borboletas', 'Dot Hutchison', 'SUSPENSE', 2017, 359, 'Perto de uma mansão isolada, existia um maravilhoso jardim. Nele, cresciam flores exuberantes, árvores frondosas... e uma coleção de preciosas ''borboletas'': jovens mulheres, sequestradas e mantidas em cativeiro por um homem brutal e obsessivo, conhecido apenas como Jardineiro. Cada uma delas passa a ser identificada pelo nome de uma espécie de borboleta, tendo, então, a pele marcada com um complexo desenho correspondente.', NULL);
INSERT INTO livros VALUES ('L0013', 'Capitães da Areia', 'Jorge Amado', 'CLASSICO', 1937, 280, 'Verdadeiro romance de formação, o livro nos torna íntimos de suas pequenas criaturas, cada uma delas com suas carências e suas ambições: do líder Pedro Bala ao religioso Pirulito, do ressentido e cruel Sem-Pernas ao aprendiz de cafetão Gato, do sensato Professor ao rústico sertanejo Volta Seca. Com a força envolvente da sua prosa, Jorge Amado nos aproxima desses garotos e nos contagia com seu intenso desejo de liberdade.', NULL);
INSERT INTO livros VALUES ('L0014', 'O Príncipe Cruel', 'Holly Black', 'FANTASIA', 2018, 322, 'Jude tinha apenas sete anos quando seus pais foram brutalmente assasinados e ela e as irmãs levadas para viver no traiçoeiro Reino das Fadas. Dez anos depois, tudo o que Jude quer é se encaixar, mesmo sendo uma garota mortal. Mas todos os feéricos parecem desprezar os humanos... Especialmente o príncipe Cardan, o mais jovem e mais perverso dos filhos do Grande Rei de Elfhame.', NULL);
INSERT INTO livros VALUES ('L0017', 'O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'INFANTIL', 1943, 96, 'O Pequeno Príncipe, escrito pelo francês Antoine de Saint-Exupéry, é uma obra atemporal que encanta leitores de todas as idades desde sua publicação, em 1943. A história narra a jornada de um garotinho com os “cabelos da cor do ouro” que vive no planeta B 612 e viaja pelo universo em busca de sabedoria e amizade. Com uma linguagem poética e delicada, Saint-Exupéry nos presenteia com uma narrativa rica em valores e que reforça a importância da simplicidade e do amor verdadeiro.', NULL);
INSERT INTO livros VALUES ('L0018', 'O Menino do Pijama Listrado', 'John Boyne', 'FICCAO', 2008, 192, 'Bruno tem nove anos e não sabe nada sobre o Holocausto e a Solução Final contra os judeus. Também não faz ideia que seu país está em guerra com boa Temporada da Europa, e muito menos que sua família está envolvida no conflito.', NULL);
INSERT INTO livros VALUES ('L0019', 'Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'CLASSICO', 1881, 320, 'Neste romance repleto de digressões filosóficas, o escritor se vale da posição privilegiada de Brás Cubas, que, como defunto autor, narra as suas desventuras e revela as contradições da sociedade brasileira do século XIX, por meio de uma análise aprofundada de seus personagens.', NULL);
INSERT INTO livros VALUES ('L0020', 'Ai Meus Deuses', 'Tera Lynn Childs', 'FANTASIA', 2008, 304, 'A vida de Phoebe Castro vira do avesso quando sua mãe anuncia que irá se casar com um estranho misterioso. Para completar, as duas terão que se mudar para o outro lado do mundo: a Grécia! Phoebe terá que dizer adeus ao sonho de cursar a mesma universidade que suas melhores amigas. Como se tudo isso não bastasse, ela ainda terá que frequentar uma escola superexclusiva na qual seu padrasto é o diretor. E os alunos são tudo, menos comuns: são descendentes dos deuses gregos e com direito a superpoderes!', NULL);
INSERT INTO livros VALUES ('L0021', '50 Ideias de Física Quântica que Você Precisa Conhecer', 'Joanne Baker', 'CIENCIA', 2015, 216, 'Em 50 ideias de Física Quântica a autora Joanne Baker explica de maneira acessível que a física quântica não é intuitiva o mundo subatômico se comporta de modo bem diferente do mundo clássico com o qual estamos familiarizados.', NULL);
INSERT INTO livros VALUES ('L0022', '50 Tons de Cinza', 'E. L. James', 'ROMANCE', 2012, 480, 'Quando Anastasia Steele entrevista o jovem empresário Christian Grey, descobre nele um homem atraente, brilhante e profundamente dominador. Ingênua e inocente, Ana se surpreende ao perceber que, a despeito da enigmática reserva de Grey, está desesperadamente atraída por ele. Incapaz de resistir à beleza discreta, à timidez e ao espírito independente de Ana, Grey admite que também a deseja ― mas em seus próprios termos.', NULL);
INSERT INTO livros VALUES ('L0023', 'Moby Dick', 'Herman Melville', 'CLASSICO', 1851, 656, 'A história do capitão Ahab, em busca de vingança contra o terrível cachalote que amputara sua perna, entrou definitivamente para a cultura popular, inspirando, entre outras criações, pinturas de Jackson Pollock e Frank Stella, adaptações de Orson Welles para o rádio e o teatro, um filme de John Huston, e até um blues do Led Zeppelin.', NULL);
INSERT INTO livros VALUES ('L0024', 'Não Conte a Ninguém', 'Harlan Coben', 'SUSPENSE', 2001, 238, 'Enquanto comemoravam o aniversário de seu primeiro beijo, o Dr. David Beck e sua esposa, Elizabeth, sofreram um terrível ataque. Ele foi golpeado e caiu no lago, inconsciente. Ela foi raptada e brutalmente assassinada por um serial killer.', NULL);
INSERT INTO livros VALUES ('L0025', 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'FANTASIA', 1997, 208, 'Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural. Pelo contrário. Até os 10 anos, Harry foi uma espécie de gata borralheira: maltratado pelos tios, herdava roupas velhas do primo gorducho, tinha óculos remendados e era tratado como um estorvo. No dia de seu aniversário de 11 anos, entretanto, ele parece deslizar por um buraco sem fundo, como o de Alice no país das maravilhas, que o conduz a um mundo mágico.', NULL);
INSERT INTO livros VALUES ('L0026', 'As Crônicas de Nárnia', 'C.S. Lewis', 'FANTASIA', 1950, 750, 'Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal - o que mais um leitor poderia querer de um livro? O livro que tem tudo isso é ''O leão, a feiticeira e o guarda-roupa'', escrito em 1949 por Clive Staples Lewis. Mas Lewis não parou por aí. Seis outros livros vieram depois e, juntos, ficaram conhecidos como ''As crônicas de Nárnia''.', NULL);
INSERT INTO livros VALUES ('L0028', 'Morro dos Ventos Uivantes', 'Emily Brontë', 'CLASSICO', 1847, 368, 'Único romance da escritora inglesa Emily Brontë, O morro dos ventos uivantes retrata uma trágica história de amor e obsessão em que os personagens principais são a obstinada e geniosa Catherine Earnshaw e seu irmão adotivo, Heathcliff. Grosseiro, humilhado e rejeitado, ele guarda apenas rancor no coração, mas tem com Catherine um relacionamento marcado por amor e ódio.', NULL);
INSERT INTO livros VALUES ('L0029', 'Orgulho e Preconceito', 'Jane Austen', 'CLASSICO', 1813, 448, 'Em Orgulho e Preconceito, Jane Austen nos apresenta os Bennets: uma família nobre, porém sem dinheiro, composta pelo pai, pela mãe e por cinco moças, todas em idade de se casar e nenhuma com direito a herdar a propriedade da família.', NULL);
INSERT INTO livros VALUES ('L0030', 'Razão e Sensibilidade', 'Jane Austen', 'CLASSICO', 1811, 400, '''Razão e Sensibilidade'' é um livro em que as irmãs Elinor e Marianne representam uma dualidade, de maneira alternada, ao longo da narrativa. As expectativas vividas pelas duas com a perda, o amor e a esperança, nos aponta para um excelente panorama da vida das mulheres de sua época.', NULL);
INSERT INTO livros VALUES ('L0031', '1984', 'George Orwell', 'FICCAO', 1949, 416, 'Winston, herói de 1984, último romance de George Orwell, vive aprisionado na engrenagem totalitária de uma sociedade completamente dominada pelo Estado, onde tudo é feito coletivamente, mas cada qual vive sozinho. Ninguém escapa à vigilância do Grande Irmão, a mais famosa personificação literária de um poder cínico e cruel ao infinito, além de vazio de sentido histórico.', NULL);
INSERT INTO livros VALUES ('L0032', 'Macunaíma', 'Mário de Andrade', 'CLASSICO', 1928, 240, 'As aventuras de Macunaíma, o anti-herói preguiçoso e sem caráter. Ele nasce negro no sertão, mas vira branco, vai para a cidade com os irmãos e se envolve com prostitutas, guerrilheiras e enfrenta todo tipo de gente em sua jornada.', NULL);
INSERT INTO livros VALUES ('L0034', 'Dom Casmurro', 'Machado de Assis', 'CLASSICO', 1899, 208, '''Dom Casmurro'' conta a história de Bento Santiago (Bentinho), apelidado de Dom Casmurro por ser calado e introvertido. Na adolescência, apaixona-se por Capítu, abandonando o seminário e, com ele, os desígnios traçados por sua mãe, Dona Glória, para que se tornasse padre.', NULL);
INSERT INTO livros VALUES ('L0035', 'O Cortiço', 'Aluísio Azevedo', 'CLASSICO', 1890, 304, 'O romance mostra as mazelas e a vida miserável dos moradores de duas habitações coletivas. João Romão é ganancioso comerciante de origem portuguesa, dono de um terreno no Rio de Janeiro onde constrói moradias de baixo custo para obter renda.', NULL);
INSERT INTO livros VALUES ('L0038', 'A Moreninha', 'Joaquim Manuel de Macedo', 'CLASSICO', 1844, 144, 'Uma leve e divertida história de amor entre um jovem estudante e uma bela moreninha nos salões do Rio de Janeiro colonial.', NULL);
INSERT INTO livros VALUES ('L0039', 'Iracema', 'José de Alencar', 'CLASSICO', 1865, 192, 'O romance conta o amor de um branco, Martim Soares Moreno, pela índia Iracema, a virgem dos lábios de mel. A relação do casal serviria de alegoria para a formação da nação brasileira.', NULL);
INSERT INTO livros VALUES ('L0040', 'O Ateneu', 'Raul Pompeia', 'CLASSICO', 1888, 147, 'Nessa obra, o narrador-personagem Sérgio conta, em caráter memorialístico, a sua experiência como interno no Ateneu, um colégio onde estudam os filhos da rica burguesia carioca do século XIX. Nessa instituição, o menino de 11 anos vai aprender a viver em uma sociedade corrupta, onde sobrevivem os mais fortes.', NULL);
INSERT INTO livros VALUES ('L0041', 'A Escrava Isaura', 'Bernardo Guimarães', 'CLASSICO', 1875, 176, 'Escrito em plena campanha abolicionista, o livro conta as desventuras de Isaura, a escrava branca, filha de Miguel, um branco ex-feitor da fazenda, e de uma escrava negra. A jovem, criada por sua senhora como se pertencesse à família, vê sua condição mudar completamente da noite para o dia.', NULL);
INSERT INTO livros VALUES ('L0042', 'O Guarani', 'José de Alencar', 'CLASSICO', 1857, 352, 'A história do amor proibido entre o índio Peri e a jovem branca. O relacionamento se concretiza com o consentimento do pai da moça, graças ao ataque dos índios Aimorés à fortaleza de sua família. É quando o fidalgo pede a Peri que salve sua filha.', NULL);
INSERT INTO livros VALUES ('L0044', 'Dom Quixote', 'Miguel de Cervantes', 'CLASSICO', 1605, 1033, 'A história mostra um ingênuo senhor rural, cujo passatempo favorito é a leitura de livros de cavalaria. O senhor acaba acreditando literalmente nas aventuras escritas e, por isso, decide tornar-se um cavaleiro andante. Suas viagens sucedem-se sob a alucinação de que estava vivendo na era da cavalaria.', NULL);
INSERT INTO livros VALUES ('L0045', 'Frankenstein', 'Mary Shelley', 'FICCAO', 1818, 240, 'O brilhante e pouco ortodoxo doutor Victor Frankenstein trabalha na criação de um monstro com Temporadas de diferentes corpos humanos. Após ser rejeitada pelo criador, a criatura escapa e passa a agir com uma violenta sede de vingança.', NULL);
INSERT INTO livros VALUES ('L0046', 'Os Três Mosqueteiros', 'Alexandre Dumas', 'CLASSICO', 1844, 672, 'Os três mosqueteiros, romance do escritor francês Alexandre Dumas, ambientado no século XVII, retrata de forma descontraída e divertida a vida francesa da época, com suas intrigas políticas e amorosas, com seus vilões e heróis, com sua nobreza e lacaios.', NULL);
INSERT INTO livros VALUES ('L0047', 'Os Miseráveis', 'Victor Hugo', 'CLASSICO', 1862, 1511, '“Os Miseráveis” conta a história de um homem que sofre durante toda sua vida por causa de um erro cometido na juventude. A saga de Jean Valjean se passa na França revolucionária do final do século XVIII e início do XIX quando monarquistas e republicanos lutavam pelas ruas.', NULL);
INSERT INTO livros VALUES ('L0048', 'O Corvo', 'Edgar Allan Poe', 'TERROR', 1845, 200, 'O enredo versa sobre os delírios de um homem após a morte de sua amada, Lenora, e trata sobre a dor da perda, a falta de esperança e a angústia da existência.', NULL);
INSERT INTO livros VALUES ('L0049', 'Madame Bovary', 'Gustave Flaubert', 'CLASSICO', 1856, 398, 'Numa pacata cidadezinha da França do século 19, Emma Bovary é a bela esposa de Charles Bovary, um médico da região. As complicações na vida de Emma começam quando ela dá início a uma aventura extraconjugal com o objetivo de se promover na sociedade, melhorar sua posição social e deixar de viver à sombra do marido.', NULL);

-- novo catalogo:
-- INSERT INTO livros VALUES ('L5000','Love, Theoretically','Ali Hazelwood','ROMANCE',2023,400,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5001','Love on the Brain','Ali Hazelwood','ROMANCE',2022,368,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5002','Not in Love','Ali Hazelwood','ROMANCE',2024,384,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5003','Book Lovers','Emily Henry','ROMANCE',2022,384,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5004','Beach Read','Emily Henry','ROMANCE',2020,384,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5005','Happy Place','Emily Henry','ROMANCE',2023,400,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5006','People We Meet on Vacation','Emily Henry','ROMANCE',2021,368,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5007','The Spanish Love Deception','Elena Armas','ROMANCE',2021,480,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5008','Yours Truly','Abby Jimenez','ROMANCE',2023,384,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5009','Part of Your World','Abby Jimenez','ROMANCE',2022,400,'Romance. Livro amplamente reconhecido. Indicado para leitores interessados em romance. ',NULL);
-- INSERT INTO livros VALUES ('L5010','Mistborn','Brandon Sanderson','FANTASIA',2006,560,'Fantasia. Livro amplamente reconhecido. Indicado para leitores interessados em fantasia. ',NULL);
-- INSERT INTO livros VALUES ('L5011','The Way of Kings','Brandon Sanderson','FANTASIA',2010,1008,'Fantasia. Livro amplamente reconhecido. Indicado para leitores interessados em fantasia. ',NULL);
-- INSERT INTO livros VALUES ('L5012','A Court of Thorns and Roses','Sarah J. Maas','FANTASIA',2015,432,'Fantasia. Livro amplamente reconhecido. Indicado para leitores interessados em fantasia. ',NULL);
-- INSERT INTO livros VALUES ('L5013','Fourth Wing','Rebecca Yarros','FANTASIA',2023,528,'Fantasia. Livro amplamente reconhecido. Indicado para leitores interessados em fantasia. ',NULL);
-- INSERT INTO livros VALUES ('L5014','Six of Crows','Leigh Bardugo','FANTASIA',2015,480,'Fantasia. Livro amplamente reconhecido. Indicado para leitores interessados em fantasia. ',NULL);
-- INSERT INTO livros VALUES ('L5015','The Silent Patient','Alex Michaelides','SUSPENSE',2019,336,'Suspense. Livro amplamente reconhecido. Indicado para leitores interessados em suspense. ',NULL);
-- INSERT INTO livros VALUES ('L5016','Gone Girl','Gillian Flynn','SUSPENSE',2012,432,'Suspense. Livro amplamente reconhecido. Indicado para leitores interessados em suspense. ',NULL);
-- INSERT INTO livros VALUES ('L5017','The Girl on the Train','Paula Hawkins','SUSPENSE',2015,378,'Suspense. Livro amplamente reconhecido. Indicado para leitores interessados em suspense. ',NULL);
-- INSERT INTO livros VALUES ('L5018','The Da Vinci Code','Dan Brown','SUSPENSE',2003,480,'Suspense. Livro amplamente reconhecido. Indicado para leitores interessados em suspense. ',NULL);
-- INSERT INTO livros VALUES ('L5019','Murder on the Orient Express','Agatha Christie','SUSPENSE',1934,256,'Suspense. Livro amplamente reconhecido. Indicado para leitores interessados em suspense. ',NULL);
-- INSERT INTO livros VALUES ('L5020','It','Stephen King','TERROR',1986,1138,'Terror. Livro amplamente reconhecido. Indicado para leitores interessados em terror. ',NULL);
-- INSERT INTO livros VALUES ('L5021','The Shining','Stephen King','TERROR',1977,447,'Terror. Livro amplamente reconhecido. Indicado para leitores interessados em terror. ',NULL);
-- INSERT INTO livros VALUES ('L5022','Pet Sematary','Stephen King','TERROR',1983,416,'Terror. Livro amplamente reconhecido. Indicado para leitores interessados em terror. ',NULL);
-- INSERT INTO livros VALUES ('L5023','Bird Box','Josh Malerman','TERROR',2014,272,'Terror. Livro amplamente reconhecido. Indicado para leitores interessados em terror. ',NULL);
-- INSERT INTO livros VALUES ('L5024','Mexican Gothic','Silvia Moreno-Garcia','TERROR',2020,320,'Terror. Livro amplamente reconhecido. Indicado para leitores interessados em terror. ',NULL);
-- INSERT INTO livros VALUES ('L5025','Dune','Frank Herbert','FICCAO',1965,688,'Ficcao. Livro amplamente reconhecido. Indicado para leitores interessados em ficcao. ',NULL);
-- INSERT INTO livros VALUES ('L5026','Foundation','Isaac Asimov','FICCAO',1951,296,'Ficcao. Livro amplamente reconhecido. Indicado para leitores interessados em ficcao. ',NULL);
-- INSERT INTO livros VALUES ('L5027','Neuromancer','William Gibson','FICCAO',1984,320,'Ficcao. Livro amplamente reconhecido. Indicado para leitores interessados em ficcao. ',NULL);
-- INSERT INTO livros VALUES ('L5028','The Martian','Andy Weir','FICCAO',2011,384,'Ficcao. Livro amplamente reconhecido. Indicado para leitores interessados em ficcao. ',NULL);
-- INSERT INTO livros VALUES ('L5029','Project Hail Mary','Andy Weir','FICCAO',2021,496,'Ficcao. Livro amplamente reconhecido. Indicado para leitores interessados em ficcao. ',NULL);
-- INSERT INTO livros VALUES ('L5030','Cosmos','Carl Sagan','CIENCIA',1980,416,'Ciencia. Livro amplamente reconhecido. Indicado para leitores interessados em ciencia. ',NULL);
-- INSERT INTO livros VALUES ('L5031','Astrophysics for People in a Hurry','Neil deGrasse Tyson','CIENCIA',2017,224,'Ciencia. Livro amplamente reconhecido. Indicado para leitores interessados em ciencia. ',NULL);
-- INSERT INTO livros VALUES ('L5032','Sapiens','Yuval Noah Harari','CIENCIA',2011,464,'Ciencia. Livro amplamente reconhecido. Indicado para leitores interessados em ciencia. ',NULL);
-- INSERT INTO livros VALUES ('L5033','The Selfish Gene','Richard Dawkins','CIENCIA',1976,360,'Ciencia. Livro amplamente reconhecido. Indicado para leitores interessados em ciencia. ',NULL);
-- INSERT INTO livros VALUES ('L5034','A Short History of Nearly Everything','Bill Bryson','CIENCIA',2003,544,'Ciencia. Livro amplamente reconhecido. Indicado para leitores interessados em ciencia. ',NULL);
-- INSERT INTO livros VALUES ('L5035','Steve Jobs','Walter Isaacson','BIOGRAFIA',2011,656,'Biografia. Livro amplamente reconhecido. Indicado para leitores interessados em biografia. ',NULL);
-- INSERT INTO livros VALUES ('L5036','Becoming','Michelle Obama','BIOGRAFIA',2018,448,'Biografia. Livro amplamente reconhecido. Indicado para leitores interessados em biografia. ',NULL);
-- INSERT INTO livros VALUES ('L5037','Long Walk to Freedom','Nelson Mandela','BIOGRAFIA',1994,656,'Biografia. Livro amplamente reconhecido. Indicado para leitores interessados em biografia. ',NULL);
-- INSERT INTO livros VALUES ('L5038','Matilda','Roald Dahl','INFANTIL',1988,240,'Infantil. Livro amplamente reconhecido. Indicado para leitores interessados em infantil. ',NULL);
-- INSERT INTO livros VALUES ('L5039','Charlotte''s Web','E. B. White','INFANTIL',1952,192,'Infantil. Livro amplamente reconhecido. Indicado para leitores interessados em infantil. ',NULL);
-- INSERT INTO livros VALUES ('L5040','The Gruffalo','Julia Donaldson','INFANTIL',1999,32,'Infantil. Livro amplamente reconhecido. Indicado para leitores interessados em infantil. ',NULL);
-- INSERT INTO livros VALUES ('L5041','Leaves of Grass','Walt Whitman','POEMA',1855,624,'Poema. Livro amplamente reconhecido. Indicado para leitores interessados em poema. ',NULL);
-- INSERT INTO livros VALUES ('L5042','The Waste Land','T. S. Eliot','POEMA',1922,80,'Poema. Livro amplamente reconhecido. Indicado para leitores interessados em poema. ',NULL);
-- INSERT INTO livros VALUES ('L5043','Crime and Punishment','Fyodor Dostoevsky','CLASSICO',1866,671,'Classico. Livro amplamente reconhecido. Indicado para leitores interessados em classico. ',NULL);
-- INSERT INTO livros VALUES ('L5044','The Brothers Karamazov','Fyodor Dostoevsky','CLASSICO',1880,824,'Classico. Livro amplamente reconhecido. Indicado para leitores interessados em classico. ',NULL);
-- INSERT INTO livros VALUES ('L5045','Anna Karenina','Leo Tolstoy','CLASSICO',1878,864,'Classico. Livro amplamente reconhecido. Indicado para leitores interessados em classico. ',NULL);
-- INSERT INTO livros VALUES ('L5046','The Count of Monte Cristo','Alexandre Dumas','CLASSICO',1844,1276,'Classico. Livro amplamente reconhecido. Indicado para leitores interessados em classico. ',NULL);
-- INSERT INTO livros VALUES ('L5047','The Odyssey','Homer','CLASSICO',-700,500,'Classico. Livro amplamente reconhecido. Indicado para leitores interessados em classico. ',NULL);

INSERT INTO livros  VALUES ('L0050', 'A Revolução dos Bichos', 'George Orwell', 'FICCAO', 1945, 152, 'Fábula política sobre animais que tomam uma fazenda e reproduzem novas formas de opressão.', NULL);
INSERT INTO livros  VALUES ('L0051', 'Admirável Mundo Novo', 'Aldous Huxley', 'FICCAO', 1932, 312, 'Distopia sobre uma sociedade tecnocrática que troca liberdade e afeto por estabilidade e consumo.', NULL);
INSERT INTO livros  VALUES ('L0052', 'Fahrenheit 451', 'Ray Bradbury', 'FICCAO', 1953, 256, 'Um bombeiro encarregado de queimar livros começa a questionar a cultura de censura em que vive.', NULL);
INSERT INTO livros  VALUES ('L0053', 'O Conto da Aia', 'Margaret Atwood', 'FICCAO', 1985, 368, 'Romance distópico sobre uma teocracia autoritária que controla o corpo e a vida das mulheres.', NULL);
INSERT INTO livros  VALUES ('L0054', 'Duna', 'Frank Herbert', 'FICCAO', 1965, 680, 'Saga de ficção científica sobre política, religião e ecologia no planeta desértico Arrakis.', NULL);
INSERT INTO livros  VALUES ('L0055', 'Fundação', 'Isaac Asimov', 'FICCAO', 1951, 256, 'Cientistas tentam preservar o conhecimento humano diante da queda prevista de um império galáctico.', NULL);
INSERT INTO livros  VALUES ('L0056', 'Eu, Robô', 'Isaac Asimov', 'FICCAO', 1950, 320, 'Coletânea de histórias que exploram robôs, inteligência artificial e dilemas das Três Leis da Robótica.', NULL);
INSERT INTO livros  VALUES ('L0057', 'Neuromancer', 'William Gibson', 'FICCAO', 1984, 320, 'Marco do cyberpunk sobre hackers, megacorporações e realidades digitais interligadas.', NULL);
INSERT INTO livros  VALUES ('L0058', 'O Fim da Infância', 'Arthur C. Clarke', 'FICCAO', 1953, 256, 'A chegada de seres superiores à Terra transforma a humanidade e provoca questões sobre evolução.', NULL);
INSERT INTO livros  VALUES ('L0059', 'Solaris', 'Stanislaw Lem', 'FICCAO', 1961, 224, 'Pesquisadores em uma estação espacial enfrentam fenômenos psicológicos causados por um planeta misterioso.', NULL);
INSERT INTO livros  VALUES ('L0060', 'O Hobbit', 'J.R.R. Tolkien', 'FANTASIA', 1937, 336, 'Bilbo Bolseiro parte em uma aventura com anões para recuperar um tesouro guardado por um dragão.', NULL);
INSERT INTO livros  VALUES ('L0061', 'O Senhor dos Anéis: As Duas Torres', 'J.R.R. Tolkien', 'FANTASIA', 1954, 448, 'A Sociedade se divide enquanto a guerra contra Sauron avança pela Terra-média.', NULL);
INSERT INTO livros  VALUES ('L0062', 'O Senhor dos Anéis: O Retorno do Rei', 'J.R.R. Tolkien', 'FANTASIA', 1955, 432, 'A jornada para destruir o Anel chega ao fim enquanto Gondor enfrenta a sombra de Mordor.', NULL);
INSERT INTO livros  VALUES ('L0063', 'Harry Potter e a Câmara Secreta', 'J.K. Rowling', 'FANTASIA', 1998, 252, 'Harry retorna a Hogwarts e investiga ataques ligados a uma antiga lenda da escola.', NULL);
INSERT INTO livros  VALUES ('L0064', 'Harry Potter e o Prisioneiro de Azkaban', 'J.K. Rowling', 'FANTASIA', 1999, 348, 'Um fugitivo de Azkaban parece ameaçar Harry, revelando segredos sobre seu passado.', NULL);
INSERT INTO livros  VALUES ('L0065', 'A Guerra dos Tronos', 'George R.R. Martin', 'FANTASIA', 1996, 592, 'Nobres disputam poder em Westeros enquanto ameaças antigas crescem além da Muralha.', NULL);
INSERT INTO livros  VALUES ('L0066', 'O Nome do Vento', 'Patrick Rothfuss', 'FANTASIA', 2007, 656, 'Kvothe narra sua juventude, seus estudos de magia e a construção de sua própria lenda.', NULL);
INSERT INTO livros  VALUES ('L0067', 'A Bússola de Ouro', 'Philip Pullman', 'FANTASIA', 1995, 368, 'Lyra viaja por um mundo de daemons, ciência e religião em busca de crianças desaparecidas.', NULL);
INSERT INTO livros  VALUES ('L0068', 'O Feiticeiro de Terramar', 'Ursula K. Le Guin', 'FANTASIA', 1968, 208, 'Um jovem mago talentoso precisa enfrentar as consequências de sua ambição e de seus erros.', NULL);
INSERT INTO livros  VALUES ('L0069', 'Mistborn: O Império Final', 'Brandon Sanderson', 'FANTASIA', 2006, 608, 'Uma ladra descobre poderes alomânticos e se junta a um plano para derrubar um tirano imortal.', NULL);
INSERT INTO livros  VALUES ('L0070', 'Cem Anos de Solidão', 'Gabriel García Márquez', 'CLASSICO', 1967, 448, 'A história da família Buendía mistura memória, política e realismo mágico em Macondo.', NULL);
INSERT INTO livros  VALUES ('L0071', 'O Amor nos Tempos do Cólera', 'Gabriel García Márquez', 'ROMANCE', 1985, 432, 'Dois personagens atravessam décadas entre espera, desejo e transformações sociais no Caribe.', NULL);
INSERT INTO livros  VALUES ('L0072', 'A Hora da Estrela', 'Clarice Lispector', 'CLASSICO', 1977, 96, 'Macabéa, jovem nordestina no Rio de Janeiro, é narrada por uma voz que questiona a própria escrita.', NULL);
INSERT INTO livros  VALUES ('L0073', 'Perto do Coração Selvagem', 'Clarice Lispector', 'CLASSICO', 1943, 208, 'Romance introspectivo que acompanha Joana em sua formação emocional e existencial.', NULL);
INSERT INTO livros  VALUES ('L0074', 'Quincas Borba', 'Machado de Assis', 'CLASSICO', 1891, 304, 'Rubião herda fortuna e filosofia de Quincas Borba, entrando em um mundo de vaidade e exploração.', NULL);
INSERT INTO livros  VALUES ('L0075', 'Esaú e Jacó', 'Machado de Assis', 'CLASSICO', 1904, 288, 'Gêmeos rivais simbolizam tensões políticas e afetivas no Brasil da virada republicana.', NULL);
INSERT INTO livros  VALUES ('L0076', 'Triste Fim de Policarpo Quaresma', 'Lima Barreto', 'CLASSICO', 1915, 224, 'Um patriota idealista confronta a burocracia, o autoritarismo e as contradições do Brasil.', NULL);
INSERT INTO livros  VALUES ('L0077', 'Clara dos Anjos', 'Lima Barreto', 'CLASSICO', 1948, 176, 'Romance sobre racismo, desigualdade e vulnerabilidade feminina no subúrbio carioca.', NULL);
INSERT INTO livros  VALUES ('L0078', 'Tenda dos Milagres', 'Jorge Amado', 'ROMANCE', 1969, 336, 'Na Bahia, a trajetória de Pedro Archanjo discute cultura popular, mestiçagem e preconceito.', NULL);
INSERT INTO livros  VALUES ('L0079', 'Dona Flor e Seus Dois Maridos', 'Jorge Amado', 'ROMANCE', 1966, 480, 'Dona Flor vive entre a lembrança do marido boêmio e a segurança de um novo casamento.', NULL);
INSERT INTO livros  VALUES ('L0080', 'A Metamorfose', 'Franz Kafka', 'CLASSICO', 1915, 96, 'Gregor Samsa acorda transformado e passa a revelar o peso da família, do trabalho e do isolamento.', NULL);
INSERT INTO livros  VALUES ('L0081', 'O Processo', 'Franz Kafka', 'CLASSICO', 1925, 272, 'Josef K. é acusado por uma justiça obscura e tenta compreender uma culpa nunca explicada.', NULL);
INSERT INTO livros  VALUES ('L0082', 'Crime e Castigo', 'Fiódor Dostoiévski', 'CLASSICO', 1866, 592, 'Raskólnikov comete um crime e é consumido por culpa, orgulho e busca de redenção.', NULL);
INSERT INTO livros  VALUES ('L0083', 'Os Irmãos Karamázov', 'Fiódor Dostoiévski', 'CLASSICO', 1880, 880, 'Drama familiar e filosófico sobre fé, culpa, liberdade e parricídio.', NULL);
INSERT INTO livros  VALUES ('L0084', 'Anna Kariênina', 'Liev Tolstói', 'CLASSICO', 1877, 864, 'Romance russo sobre amor, casamento, hipocrisia social e busca de sentido.', NULL);
INSERT INTO livros  VALUES ('L0085', 'Guerra e Paz', 'Liev Tolstói', 'CLASSICO', 1869, 1225, 'Panorama da sociedade russa durante as guerras napoleônicas, combinando história e vida íntima.', NULL);
INSERT INTO livros  VALUES ('L0086', 'O Estrangeiro', 'Albert Camus', 'CLASSICO', 1942, 144, 'Meursault encara a vida, o crime e o julgamento com uma indiferença que expõe o absurdo.', NULL);
INSERT INTO livros  VALUES ('L0087', 'A Peste', 'Albert Camus', 'CLASSICO', 1947, 288, 'Uma cidade isolada por uma epidemia revela escolhas morais diante do sofrimento coletivo.', NULL);
INSERT INTO livros  VALUES ('L0088', 'O Velho e o Mar', 'Ernest Hemingway', 'CLASSICO', 1952, 128, 'Um pescador cubano enfrenta um enorme peixe em uma luta de resistência e dignidade.', NULL);
INSERT INTO livros  VALUES ('L0089', 'O Sol é Para Todos', 'Harper Lee', 'CLASSICO', 1960, 384, 'Uma criança observa injustiça racial e coragem moral no sul dos Estados Unidos.', NULL);
INSERT INTO livros  VALUES ('L0090', 'O Apanhador no Campo de Centeio', 'J.D. Salinger', 'CLASSICO', 1951, 256, 'Holden Caulfield narra sua crise adolescente entre rejeição social e fragilidade emocional.', NULL);
INSERT INTO livros  VALUES ('L0091', 'Lolita', 'Vladimir Nabokov', 'CLASSICO', 1955, 336, 'Narrativa controversa em que um narrador manipulador expõe obsessão, abuso e autoengano.', NULL);
INSERT INTO livros  VALUES ('L0092', 'Ulisses', 'James Joyce', 'CLASSICO', 1922, 736, 'Um dia em Dublin é narrado por técnicas modernistas que exploram consciência, linguagem e cotidiano.', NULL);
INSERT INTO livros  VALUES ('L0093', 'Mrs. Dalloway', 'Virginia Woolf', 'CLASSICO', 1925, 224, 'Um dia na vida de Clarissa Dalloway revela memórias, traumas e contrastes da sociedade inglesa.', NULL);
INSERT INTO livros  VALUES ('L0094', 'Ao Farol', 'Virginia Woolf', 'CLASSICO', 1927, 240, 'Família, passagem do tempo e percepção subjetiva se organizam em torno de uma viagem desejada.', NULL);
INSERT INTO livros  VALUES ('L0095', 'O Grande Gatsby', 'F. Scott Fitzgerald', 'CLASSICO', 1925, 208, 'Nos anos 1920, riqueza, amor idealizado e frustração marcam a trajetória de Jay Gatsby.', NULL);
INSERT INTO livros  VALUES ('L0096', 'As Vinhas da Ira', 'John Steinbeck', 'CLASSICO', 1939, 528, 'Uma família migra durante a Grande Depressão em busca de trabalho e dignidade.', NULL);
INSERT INTO livros  VALUES ('L0097', 'Ratos e Homens', 'John Steinbeck', 'CLASSICO', 1937, 112, 'Dois trabalhadores rurais sonham com estabilidade em meio à pobreza e à violência social.', NULL);
INSERT INTO livros  VALUES ('L0098', 'Beloved', 'Toni Morrison', 'CLASSICO', 1987, 352, 'Uma mulher sobrevivente da escravidão é assombrada por memórias e perdas familiares.', NULL);
INSERT INTO livros  VALUES ('L0099', 'A Cor Púrpura', 'Alice Walker', 'ROMANCE', 1982, 304, 'Cartas de Celie narram abuso, amizade, espiritualidade e reconstrução de identidade.', NULL);
INSERT INTO livros  VALUES ('L0100', 'Ensaio Sobre a Cegueira', 'José Saramago', 'FICCAO', 1995, 312, 'Uma epidemia de cegueira branca expõe medo, brutalidade e solidariedade em colapso social.', NULL);
INSERT INTO livros  VALUES ('L0101', 'O Evangelho Segundo Jesus Cristo', 'José Saramago', 'FICCAO', 1991, 448, 'Releitura literária da vida de Jesus com foco em humanidade, destino e poder religioso.', NULL);
INSERT INTO livros  VALUES ('L0102', 'Memorial do Convento', 'José Saramago', 'CLASSICO', 1982, 384, 'No Portugal do século XVIII, personagens reais e ficcionais cruzam fé, poder e sonho de voo.', NULL);
INSERT INTO livros  VALUES ('L0103', 'A Sombra do Vento', 'Carlos Ruiz Zafón', 'SUSPENSE', 2001, 576, 'Um jovem encontra um livro raro e mergulha em mistérios literários na Barcelona do pós-guerra.', NULL);
INSERT INTO livros  VALUES ('L0104', 'O Nome da Rosa', 'Umberto Eco', 'SUSPENSE', 1980, 576, 'Monges investigam mortes em uma abadia medieval marcada por disputas teológicas e segredos.', NULL);
INSERT INTO livros  VALUES ('L0105', 'Assassinato no Expresso do Oriente', 'Agatha Christie', 'SUSPENSE', 1934, 256, 'Hercule Poirot investiga um assassinato em um trem bloqueado pela neve.', NULL);
INSERT INTO livros  VALUES ('L0106', 'E Não Sobrou Nenhum', 'Agatha Christie', 'SUSPENSE', 1939, 264, 'Dez pessoas isoladas em uma ilha morrem uma a uma conforme acusações do passado vêm à tona.', NULL);
INSERT INTO livros  VALUES ('L0107', 'Morte no Nilo', 'Agatha Christie', 'SUSPENSE', 1937, 288, 'Hercule Poirot investiga um assassinato ocorrido durante uma viagem de barco pelo rio Nilo.', NULL);
INSERT INTO livros  VALUES ('L0108', 'O Código Da Vinci', 'Dan Brown', 'SUSPENSE', 2003, 480, 'Um simbologista investiga pistas envolvendo arte, religião e sociedades secretas.', NULL);
INSERT INTO livros  VALUES ('L0109', 'Anjos e Demônios', 'Dan Brown', 'SUSPENSE', 2000, 464, 'Robert Langdon acompanha uma investigação que une ciência, Vaticano e conspirações históricas.', NULL);
INSERT INTO livros  VALUES ('L0110', 'Garota Exemplar', 'Gillian Flynn', 'SUSPENSE', 2012, 448, 'O desaparecimento de Amy Dunne revela camadas de manipulação em um casamento em crise.', NULL);
INSERT INTO livros  VALUES ('L0111', 'O Silêncio dos Inocentes', 'Thomas Harris', 'SUSPENSE', 1988, 352, 'Uma agente do FBI busca ajuda de Hannibal Lecter para capturar um assassino em série.', NULL);
INSERT INTO livros  VALUES ('L0112', 'O Iluminado', 'Stephen King', 'TERROR', 1977, 464, 'Uma família isolada em um hotel enfrenta forças sobrenaturais e a deterioração psicológica do pai.', NULL);
INSERT INTO livros  VALUES ('L0113', 'It: A Coisa', 'Stephen King', 'TERROR', 1986, 1104, 'Amigos enfrentam uma entidade que retorna periodicamente para aterrorizar uma cidade.', NULL);
INSERT INTO livros  VALUES ('L0114', 'Carrie, a Estranha', 'Stephen King', 'TERROR', 1974, 199, 'Uma adolescente rejeitada descobre poderes telecinéticos e reage à violência que sofre.', NULL);
INSERT INTO livros  VALUES ('L0115', 'A Assombração da Casa da Colina', 'Shirley Jackson', 'TERROR', 1959, 256, 'Pesquisadores e convidados investigam uma casa cuja presença parece afetar todos ao redor.', NULL);
INSERT INTO livros  VALUES ('L0116', 'O Médico e o Monstro', 'Robert Louis Stevenson', 'TERROR', 1886, 144, 'Um cientista divide sua personalidade e revela o lado sombrio da moral vitoriana.', NULL);
INSERT INTO livros  VALUES ('L0117', 'A Volta do Parafuso', 'Henry James', 'TERROR', 1898, 160, 'Uma governanta acredita ver presenças sobrenaturais envolvendo duas crianças sob seus cuidados.', NULL);
INSERT INTO livros  VALUES ('L0118', 'Entrevista com o Vampiro', 'Anne Rice', 'TERROR', 1976, 384, 'Um vampiro narra sua existência marcada por culpa, desejo e imortalidade.', NULL);
INSERT INTO livros  VALUES ('L0119', 'Coraline', 'Neil Gaiman', 'TERROR', 2002, 192, 'Uma menina encontra uma versão alternativa de sua casa, sedutora e perigosa.', NULL);
INSERT INTO livros  VALUES ('L0120', 'Americanah', 'Chimamanda Ngozi Adichie', 'ROMANCE', 2013, 520, 'Ifemelu atravessa Nigéria, Estados Unidos e Inglaterra refletindo sobre amor, raça e pertencimento.', NULL);
INSERT INTO livros  VALUES ('L0121', 'Meio Sol Amarelo', 'Chimamanda Ngozi Adichie', 'ROMANCE', 2006, 504, 'Personagens vivem amor, guerra e perda durante o conflito de Biafra na Nigéria.', NULL);
INSERT INTO livros  VALUES ('L0122', 'Hibisco Roxo', 'Chimamanda Ngozi Adichie', 'ROMANCE', 2003, 336, 'Uma adolescente nigeriana cresce entre fé rígida, violência familiar e despertar político.', NULL);
INSERT INTO livros  VALUES ('L0123', 'A Menina que Roubava Livros', 'Markus Zusak', 'FICCAO', 2005, 480, 'Durante a Segunda Guerra, uma menina encontra nos livros uma forma de enfrentar perdas e medo.', NULL);
INSERT INTO livros  VALUES ('L0124', 'O Caçador de Pipas', 'Khaled Hosseini', 'ROMANCE', 2003, 368, 'Amizade, culpa e redenção atravessam a vida de dois meninos no Afeganistão.', NULL);
INSERT INTO livros  VALUES ('L0125', 'A Cidade do Sol', 'Khaled Hosseini', 'ROMANCE', 2007, 384, 'Duas mulheres afegãs constroem uma relação de resistência em meio à guerra e à opressão.', NULL);
INSERT INTO livros  VALUES ('L0126', 'A Insustentável Leveza do Ser', 'Milan Kundera', 'ROMANCE', 1984, 336, 'Relacionamentos e escolhas íntimas se entrelaçam com a política da Tchecoslováquia ocupada.', NULL);
INSERT INTO livros  VALUES ('L0127', 'O Deus das Pequenas Coisas', 'Arundhati Roy', 'ROMANCE', 1997, 368, 'Gêmeos indianos revisitam traumas familiares, castas e regras sociais que moldaram suas vidas.', NULL);
INSERT INTO livros  VALUES ('L0128', 'A Amiga Genial', 'Elena Ferrante', 'ROMANCE', 2011, 336, 'Duas amigas crescem em Nápoles, entre rivalidade, afeto e limites impostos pelo ambiente social.', NULL);
INSERT INTO livros  VALUES ('L0129', 'Normal People', 'Sally Rooney', 'ROMANCE', 2018, 288, 'Connell e Marianne vivem uma relação marcada por classe, insegurança e desencontros emocionais.', NULL);
INSERT INTO livros  VALUES ('L0130', 'O Alquimista', 'Paulo Coelho', 'ROMANCE', 1988, 176, 'Um jovem pastor parte em busca de um tesouro e encontra uma jornada espiritual de autoconhecimento.', NULL);
INSERT INTO livros  VALUES ('L0131', 'Veronika Decide Morrer', 'Paulo Coelho', 'ROMANCE', 1998, 240, 'Uma jovem internada após tentativa de suicídio passa a repensar liberdade, loucura e desejo de viver.', NULL);
INSERT INTO livros  VALUES ('L0132', 'O Diário de Anne Frank', 'Anne Frank', 'BIOGRAFIA', 1947, 352, 'Relato de uma adolescente judia escondida com a família durante a perseguição nazista.', NULL);
INSERT INTO livros  VALUES ('L0133', 'Eu Sei Por Que o Pássaro Canta na Gaiola', 'Maya Angelou', 'BIOGRAFIA', 1969, 304, 'Memórias de infância e juventude marcadas por racismo, violência e descoberta da própria voz.', NULL);
INSERT INTO livros  VALUES ('L0134', 'Longa Caminhada até a Liberdade', 'Nelson Mandela', 'BIOGRAFIA', 1994, 656, 'Autobiografia de Mandela sobre infância, militância, prisão e luta contra o apartheid.', NULL);
INSERT INTO livros  VALUES ('L0135', 'Steve Jobs', 'Walter Isaacson', 'BIOGRAFIA', 2011, 656, 'Biografia baseada em entrevistas que acompanha a vida, a liderança e as contradições de Steve Jobs.', NULL);
INSERT INTO livros  VALUES ('L0136', 'Einstein: Sua Vida, Seu Universo', 'Walter Isaacson', 'BIOGRAFIA', 2007, 704, 'Biografia que apresenta a vida científica, política e pessoal de Albert Einstein.', NULL);
INSERT INTO livros  VALUES ('L0137', 'Minha Breve História', 'Stephen Hawking', 'BIOGRAFIA', 2013, 144, 'Relato autobiográfico de Hawking sobre ciência, doença, família e carreira acadêmica.', NULL);
INSERT INTO livros  VALUES ('L0138', 'Sapiens: Uma Breve História da Humanidade', 'Yuval Noah Harari', 'CIENCIA', 2011, 464, 'Síntese histórica sobre a evolução humana, cultura, agricultura, impérios e modernidade.', NULL);
INSERT INTO livros  VALUES ('L0139', 'Homo Deus', 'Yuval Noah Harari', 'CIENCIA', 2015, 448, 'Discussão sobre tecnologia, biotecnologia, inteligência artificial e futuros possíveis da humanidade.', NULL);
INSERT INTO livros  VALUES ('L0140', 'A Origem das Espécies', 'Charles Darwin', 'CIENCIA', 1859, 502, 'Obra fundamental que apresenta a seleção natural como explicação para a diversidade da vida.', NULL);
INSERT INTO livros  VALUES ('L0141', 'Cosmos', 'Carl Sagan', 'CIENCIA', 1980, 384, 'Viagem acessível pela astronomia, história da ciência e lugar da humanidade no universo.', NULL);
INSERT INTO livros  VALUES ('L0142', 'Pálido Ponto Azul', 'Carl Sagan', 'CIENCIA', 1994, 384, 'Reflexão sobre exploração espacial, ciência e a fragilidade da Terra vista do cosmos.', NULL);
INSERT INTO livros  VALUES ('L0143', 'O Gene Egoísta', 'Richard Dawkins', 'CIENCIA', 1976, 384, 'Introdução à evolução centrada nos genes e à ideia dos memes culturais.', NULL);
INSERT INTO livros  VALUES ('L0144', 'O Andar do Bêbado', 'Leonard Mlodinow', 'CIENCIA', 2008, 272, 'Livro de divulgação sobre acaso, probabilidade e como interpretamos eventos aleatórios.', NULL);
INSERT INTO livros  VALUES ('L0145', 'Rápido e Devagar: Duas Formas de Pensar', 'Daniel Kahneman', 'CIENCIA', 2011, 608, 'Apresenta pesquisas sobre julgamento, vieses cognitivos e tomada de decisão.', NULL);
INSERT INTO livros  VALUES ('L0146', 'O Mundo de Sofia', 'Jostein Gaarder', 'FICCAO', 1991, 560, 'Uma adolescente recebe lições misteriosas que percorrem a história da filosofia.', NULL);
INSERT INTO livros  VALUES ('L0147', 'Alice no País das Maravilhas', 'Lewis Carroll', 'INFANTIL', 1865, 160, 'Alice entra em um mundo absurdo onde lógica, linguagem e imaginação se transformam constantemente.', NULL);
INSERT INTO livros  VALUES ('L0148', 'O Mágico de Oz', 'L. Frank Baum', 'INFANTIL', 1900, 224, 'Dorothy viaja por Oz com amigos que buscam coragem, coração, inteligência e retorno para casa.', NULL);
INSERT INTO livros  VALUES ('L0149', 'Matilda', 'Roald Dahl', 'INFANTIL', 1988, 240, 'Uma menina brilhante enfrenta adultos cruéis e descobre poderes ligados à sua inteligência.', NULL);

INSERT INTO livros  VALUES ('L0150', 'A Ilha do Tesouro', 'Robert Louis Stevenson', 'CLASSICO', 1883, 272, 'Jim Hawkins parte em uma aventura marítima envolvendo piratas, mapa secreto e busca por tesouro.', NULL);
INSERT INTO livros  VALUES ('L0151', 'Robinson Crusoé', 'Daniel Defoe', 'CLASSICO', 1719, 320, 'Um náufrago sobrevive por anos em uma ilha, reorganizando trabalho, fé e solidão.', NULL);
INSERT INTO livros  VALUES ('L0152', 'Viagem ao Centro da Terra', 'Júlio Verne', 'FICCAO', 1864, 280, 'Professor e sobrinho entram por um vulcão em uma expedição fantástica ao interior do planeta.', NULL);
INSERT INTO livros  VALUES ('L0153', 'Vinte Mil Léguas Submarinas', 'Júlio Verne', 'FICCAO', 1870, 448, 'O capitão Nemo conduz viajantes pelo fundo do mar a bordo do submarino Nautilus.', NULL);
INSERT INTO livros  VALUES ('L0154', 'A Volta ao Mundo em 80 Dias', 'Júlio Verne', 'FICCAO', 1873, 256, 'Phileas Fogg aposta que conseguirá completar uma volta ao mundo em prazo quase impossível.', NULL);
INSERT INTO livros  VALUES ('L0155', 'A Máquina do Tempo', 'H.G. Wells', 'FICCAO', 1895, 144, 'Um inventor viaja ao futuro distante e encontra uma humanidade dividida por novas formas sociais.', NULL);
INSERT INTO livros  VALUES ('L0156', 'A Guerra dos Mundos', 'H.G. Wells', 'FICCAO', 1898, 224, 'Marcianos invadem a Terra, expondo a fragilidade humana diante de uma tecnologia superior.', NULL);
INSERT INTO livros  VALUES ('L0157', 'O Homem Invisível', 'H.G. Wells', 'FICCAO', 1897, 192, 'Um cientista invisível perde controle sobre sua descoberta e sobre a própria moralidade.', NULL);
INSERT INTO livros  VALUES ('L0158', 'Contato', 'Carl Sagan', 'FICCAO', 1985, 432, 'Uma cientista interpreta sinais extraterrestres e enfrenta disputas entre ciência, fé e política.', NULL);
INSERT INTO livros  VALUES ('L0159', 'O Guia do Mochileiro das Galáxias', 'Douglas Adams', 'FICCAO', 1979, 208, 'Arthur Dent é levado ao espaço em uma comédia sobre burocracia, absurdo e sobrevivência cósmica.', NULL);
INSERT INTO livros  VALUES ('L0160', 'Androides Sonham com Ovelhas Elétricas?', 'Philip K. Dick', 'FICCAO', 1968, 240, 'Um caçador de androides questiona humanidade, empatia e identidade em um futuro pós-apocalíptico.', NULL);
INSERT INTO livros  VALUES ('L0161', 'O Homem do Castelo Alto', 'Philip K. Dick', 'FICCAO', 1962, 288, 'História alternativa imagina um mundo em que as potências do Eixo venceram a Segunda Guerra.', NULL);
INSERT INTO livros  VALUES ('L0162', 'Snow Crash', 'Neal Stephenson', 'FICCAO', 1992, 480, 'Hackers, corporações e linguagem se misturam em uma visão acelerada de mundos virtuais.', NULL);
INSERT INTO livros  VALUES ('L0163', 'Jogador Número 1', 'Ernest Cline', 'FICCAO', 2011, 464, 'Em um futuro desigual, jovens competem em um universo virtual por herança e controle tecnológico.', NULL);
INSERT INTO livros  VALUES ('L0164', 'O Problema dos Três Corpos', 'Liu Cixin', 'FICCAO', 2008, 320, 'Cientistas investigam sinais alienígenas ligados à Revolução Cultural e a uma ameaça cósmica.', NULL);
INSERT INTO livros  VALUES ('L0165', 'O Marciano', 'Andy Weir', 'FICCAO', 2011, 336, 'Um astronauta abandonado em Marte usa ciência e engenhosidade para tentar sobreviver.', NULL);
INSERT INTO livros  VALUES ('L0166', 'Projeto Hail Mary', 'Andy Weir', 'FICCAO', 2021, 496, 'Um cientista acorda sozinho em uma missão espacial decisiva para salvar a Terra.', NULL);
INSERT INTO livros  VALUES ('L0167', 'A Mão Esquerda da Escuridão', 'Ursula K. Le Guin', 'FICCAO', 1969, 304, 'Diplomata humano visita um planeta onde gênero, política e confiança seguem outras regras.', NULL);
INSERT INTO livros  VALUES ('L0168', 'Os Despossuídos', 'Ursula K. Le Guin', 'FICCAO', 1974, 384, 'Dois mundos opostos permitem discutir anarquismo, ciência, liberdade e pertencimento.', NULL);
INSERT INTO livros  VALUES ('L0169', 'Kindred', 'Octavia E. Butler', 'FICCAO', 1979, 288, 'Uma escritora negra é puxada para o passado escravista dos Estados Unidos e confronta sua ancestralidade.', NULL);
INSERT INTO livros  VALUES ('L0170', 'A Quinta Estação', 'N.K. Jemisin', 'FANTASIA', 2015, 512, 'Em um mundo devastado por catástrofes, pessoas com poderes geológicos enfrentam perseguição e colapso.', NULL);
INSERT INTO livros  VALUES ('L0171', 'Deuses Americanos', 'Neil Gaiman', 'FANTASIA', 2001, 560, 'Um ex-presidiário cruza os Estados Unidos em meio a antigos deuses e novas divindades culturais.', NULL);
INSERT INTO livros  VALUES ('L0172', 'Lugar Nenhum', 'Neil Gaiman', 'FANTASIA', 1996, 400, 'Um homem comum descobre uma Londres subterrânea cheia de perigos, alianças e regras próprias.', NULL);
INSERT INTO livros  VALUES ('L0173', 'Stardust', 'Neil Gaiman', 'FANTASIA', 1999, 256, 'Um jovem atravessa uma muralha para buscar uma estrela caída e encontra um reino mágico.', NULL);
INSERT INTO livros  VALUES ('L0174', 'A Cor da Magia', 'Terry Pratchett', 'FANTASIA', 1983, 288, 'Primeiro livro do Discworld, satiriza convenções da fantasia por meio de aventuras absurdas.', NULL);
INSERT INTO livros  VALUES ('L0175', 'O Último Desejo', 'Andrzej Sapkowski', 'FANTASIA', 1993, 320, 'Contos apresentam Geralt de Rívia, caçador de monstros em um mundo moralmente ambíguo.', NULL);
INSERT INTO livros  VALUES ('L0176', 'A Roda do Tempo: O Olho do Mundo', 'Robert Jordan', 'FANTASIA', 1990, 688, 'Jovens de uma aldeia são lançados em uma jornada ligada a profecias e forças antigas.', NULL);
INSERT INTO livros  VALUES ('L0177', 'O Último Reino', 'Bernard Cornwell', 'FICCAO', 2004, 368, 'Uhtred cresce entre saxões e vikings durante a formação dos reinos ingleses.', NULL);
INSERT INTO livros  VALUES ('L0178', 'Xógum', 'James Clavell', 'FICCAO', 1975, 1152, 'Um navegador inglês chega ao Japão feudal e se envolve em disputas políticas e culturais.', NULL);
INSERT INTO livros  VALUES ('L0179', 'O Perfume', 'Patrick Süskind', 'SUSPENSE', 1985, 272, 'Um homem de olfato extraordinário desenvolve obsessão por criar o perfume perfeito.', NULL);
INSERT INTO livros  VALUES ('L0180', 'O Talentoso Ripley', 'Patricia Highsmith', 'SUSPENSE', 1955, 320, 'Tom Ripley mergulha em fraude, desejo e assassinato ao tentar ocupar uma vida que inveja.', NULL);
INSERT INTO livros  VALUES ('L0181', 'Strangers on a Train', 'Patricia Highsmith', 'SUSPENSE', 1950, 256, 'Dois homens conversam sobre trocar assassinatos, iniciando uma trama de chantagem e culpa.', NULL);
INSERT INTO livros  VALUES ('L0182', 'A Garota no Trem', 'Paula Hawkins', 'SUSPENSE', 2015, 384, 'Uma mulher observa vidas alheias pela janela do trem e se envolve em um desaparecimento.', NULL);
INSERT INTO livros  VALUES ('L0183', 'Antes de Dormir', 'S.J. Watson', 'SUSPENSE', 2011, 368, 'Uma mulher sem memória recente tenta reconstruir sua vida por meio de anotações diárias.', NULL);
INSERT INTO livros  VALUES ('L0184', 'Misery', 'Stephen King', 'TERROR', 1987, 352, 'Um escritor ferido é mantido preso por uma fã obcecada que exige a volta de sua personagem favorita.', NULL);
INSERT INTO livros  VALUES ('L0185', 'Cemitério Maldito', 'Stephen King', 'TERROR', 1983, 424, 'Uma família descobre um terreno capaz de trazer mortos de volta com consequências terríveis.', NULL);
INSERT INTO livros  VALUES ('L0186', 'O Chamado de Cthulhu', 'H.P. Lovecraft', 'TERROR', 1928, 128, 'Relatos fragmentados revelam um culto antigo e uma entidade cósmica adormecida.', NULL);
INSERT INTO livros  VALUES ('L0187', 'Nas Montanhas da Loucura', 'H.P. Lovecraft', 'TERROR', 1936, 176, 'Expedição antártica encontra ruínas antigas e horrores ligados à história pré-humana da Terra.', NULL);
INSERT INTO livros  VALUES ('L0188', 'A Mulher de Branco', 'Wilkie Collins', 'SUSPENSE', 1859, 672, 'Mistério vitoriano envolvendo identidade, herança, conspiração e uma aparição na estrada.', NULL);
INSERT INTO livros  VALUES ('L0189', 'A Pedra da Lua', 'Wilkie Collins', 'SUSPENSE', 1868, 528, 'O roubo de uma joia indiana dá origem a uma investigação narrada por múltiplas vozes.', NULL);
INSERT INTO livros  VALUES ('L0190', 'Persuasão', 'Jane Austen', 'CLASSICO', 1817, 256, 'Anne Elliot reencontra um antigo amor e reconsidera escolhas feitas sob pressão familiar.', NULL);
INSERT INTO livros  VALUES ('L0191', 'Emma', 'Jane Austen', 'CLASSICO', 1815, 432, 'Uma jovem rica tenta formar casais ao seu redor enquanto aprende sobre vaidade e autoconhecimento.', NULL);
INSERT INTO livros  VALUES ('L0192', 'Jane Eyre', 'Charlotte Brontë', 'CLASSICO', 1847, 624, 'Órfã independente enfrenta privações, amor e segredos em busca de autonomia moral.', NULL);
INSERT INTO livros  VALUES ('L0193', 'Norte e Sul', 'Elizabeth Gaskell', 'CLASSICO', 1855, 544, 'Mudança para uma cidade industrial aproxima conflitos de classe, trabalho e romance.', NULL);
INSERT INTO livros  VALUES ('L0194', 'Middlemarch', 'George Eliot', 'CLASSICO', 1871, 880, 'Vidas de uma cidade inglesa revelam ambição, casamento, política e limites sociais.', NULL);
INSERT INTO livros  VALUES ('L0195', 'David Copperfield', 'Charles Dickens', 'CLASSICO', 1850, 768, 'Narrativa de formação acompanha perdas, trabalho, amizade e amadurecimento de David.', NULL);
INSERT INTO livros  VALUES ('L0196', 'Grandes Esperanças', 'Charles Dickens', 'CLASSICO', 1861, 544, 'Pip ascende socialmente enquanto enfrenta culpa, amor idealizado e revelações sobre sua fortuna.', NULL);
INSERT INTO livros  VALUES ('L0197', 'Oliver Twist', 'Charles Dickens', 'CLASSICO', 1838, 480, 'Um órfão atravessa pobreza, crime e exploração na Londres do século XIX.', NULL);
INSERT INTO livros  VALUES ('L0198', 'O Conde de Monte Cristo', 'Alexandre Dumas', 'CLASSICO', 1844, 1248, 'Edmond Dantès escapa da prisão e executa uma longa vingança contra quem o traiu.', NULL);
INSERT INTO livros  VALUES ('L0199', 'A Dama das Camélias', 'Alexandre Dumas Filho', 'ROMANCE', 1848, 256, 'Romance trágico sobre amor, doença e julgamento social na Paris do século XIX.', NULL);
