CREATE EXTENSION IF NOT EXISTS vector;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'genero_enum'
    ) THEN
        CREATE TYPE genero_enum AS ENUM (
            'ROMANCE',
            'FANTASIA',
            'FICCAO',
            'TERROR',
            'SUSPENSE',
            'CIENCIA',
            'BIOGRAFIA',
            'CLASSICO',
            'INFANTIL',
            'POEMA',
            'OUTRO'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS livros (
    id VARCHAR(20) PRIMARY KEY,
    titulo VARCHAR(255),
    autor VARCHAR(255),
    genero genero_enum DEFAULT 'OUTRO',
    ano INT,
    numero_paginas INT,
    descricao TEXT,
    embedding VECTOR(384)
);

-- Para uma base pequena, a busca exata já é suficiente.
-- Em bases maiores, este índice acelera a distância por cosseno.
CREATE INDEX IF NOT EXISTS livros_embedding_hnsw_idx
ON livros USING hnsw (embedding vector_cosine_ops);

-- INSERTS

INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('81258637','The Bastard Son & The Devil Himself','Colleen Hoover',2022,368,'Caught between two warring clans, the son of a notorious witch responsible for a deadly massacre tries to find his place in the world — and his powers.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0001','É assim que começa','Colleen Hoover',2022,336,'“Lily e o seu ex-marido, Ryle, acabaram de se adaptar numa situação de compartilhamento de guarda quando, de repente, ela se reencontra com seu primeiro amor, Atlas. Depois de quase dois anos separados, o tempo finalmente parece estar ao favor de ambos, e Lily imediatamente aceita o convite para um encontro.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0002','A Hipótese do Amor','Ali Hazelwood',2022,453,'Olive Smith, aluna do doutorado em Biologia da Universidade Stanford, acredita na ciência – não em algo incontrolável como o amor.Depois de sair algumas vezes com Jeremy, ela percebe que sua melhor amiga gosta dele e decide juntá-los. Para mostrar que está feliz com essa escolha, Olive precisa ser convincente: afinal, cientistas exigem provas.Sem muitas opções, ela resolve inventar um namoro de mentira e, num momento de pânico, beija o primeiro homem que vê pela frente.O problema é que esse homem é Adam Carlsen, um jovem professor de prestígio – conhecido por levar os alunos às lágrimas. Por isso, Olive fica chocada quando o tirano dos laboratórios concorda em levar adiante a farsa e fingir ser seu namorado.De repente, seu pequeno experimento parece perigosamente próximo da combustão e aquela pequena possibilidade científica, que era apenas uma hipótese sobre o amor, transforma-se em algo totalmente inesperado.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0003','Uma Breve História do Tempo','Stephen Hawking',1988,256,'Uma das mentes mais geniais do mundo moderno, Stephen Hawking guia o leitor na busca por respostas a algumas das maiores dúvidas da humanidade: Qual a origem do universo? Ele é infinito? E o tempo? Sempre existiu, ou houve um começo e haverá um fim? Existem outras dimensões além das três espaciais? E o que vai acontecer quando tudo terminar?');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0004','O Universo Numa Casca de Noz','Stephen Hawking',2001,223,'Após o enorme sucesso de Uma breve história do tempo, a Intrínseca traz a luxuosa reedição de O universo numa casca de noz, na qual Stephen Hawking se vale de ilustrações, fotos e esquemas detalhados para mostrar grandes descobertas no campo da física teórica. Tudo isso, é claro, com sua conhecida clareza, elucidando temas complexos por meio de conceitos e ideias do dia a dia, como a inflação, as cartas de baralho e as linhas ferroviárias, e permeado com seu peculiar senso de humor.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0005','O Universo Elegante','Brian Greene',1999,480,'Tudo o que existe e acontece no mundo, no universo, surge das vibrações dessas entidades centenas de bilhões e bilhões de vezes menores do que o núcleo de um átomo. Hoje, no mundo inteiro, físicos e matemáticos trabalham febrilmente com a idéia de ''cordas''.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0006','Breves Respostas para Grandes Questões','Stephen Hawking',2018,256,'Nessa obra inédita de um dos maiores gênios da física moderna, investigamos questões que encantam a humanidade desde os primórdios da sociedade até a atualidade, como a existência de Deus, de vida inteligente fora da Terra ou o início do universo.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0007','O Homem de Giz','C. J. Tudor',2018,272,'Em 2016, Eddie e seus amigos, já com certa idade, recebem uma carta com um desenho de um homem de giz enforcado. Ocorre, então, que um de seus amigos repentinamente aparece morto. Eddie não tem dúvidas de que precisa descobrir quem cometeu o crime e como isso se relaciona com o passado de 30 anos atrás.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0008','Manual de Assassinato para Boas Garotas','Holly Jackson',2022,448,'Na história, Pippa Fitz-Amobi está prestes a concluir o seu ensino médio e decide fazer o seu projeto de conclusão de curso sobre a investigação do caso Andie Bell: a garota mais bonita e popular da escola assassinada em 2012 por seu namorado, Sal Singh, que cometeu suicídio dias após o crime.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0009','Anatomia do Mal','Harold Schechter',2013,480,'O que faz gente aparentemente normal começar a matar e não parar mais? O que move - e o que pode deter - assassinos em série como Ed Gein, o psicopata americano que inspirou os mais célebres maníacos do cinema, como Norman Bates (Psicose), Leatherface (O Massacre da Serra Elétrica) e Hannibal Lecter (O Silêncio dos Inocentes). Como explicar a compulsão por matar e o prazer de causar dor, sem qualquer arrependimento? De onde vem tanta fúria? As respostas estão no novo lançamento da editora DarkSide Books: Serial Killers - Anatomia do Mal, dossiê definitivo sobre o universo sombrio dos psicopatas mais perversos da história.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0010','Os Sertões','Euclides da Cunha',1902,664,'A obra trata da Guerra de Canudos que aconteceu no interior da Bahia. O autor, que era correspondente do jornal O Estado de São Paulo, presenciou Temporada dos acontecimentos na região e os descreveu de forma fiel. Além de desenvolver um romance histórico que mistura uma narrativa literária, sociológica e geográfica.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0011','O Gato Malhado e a Andorinha Sinhá','Jorge Amado',1978,128,'Com grande lirismo, Jorge Amado narra a história do amor de um gato mau por uma adorável andorinha. Com ilustrações aquareladas do artista plástico Carybé, a narrativa mostra como duas criaturas bem diferentes podem não apenas conviver em paz como mudar a maneira que cada um tem de ver o mundo.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0012','O Jardim das Borboletas','Dot Hutchison',2017,359,'Perto de uma mansão isolada, existia um maravilhoso jardim. Nele, cresciam flores exuberantes, árvores frondosas... e uma coleção de preciosas ''borboletas'': jovens mulheres, sequestradas e mantidas em cativeiro por um homem brutal e obsessivo, conhecido apenas como Jardineiro. Cada uma delas passa a ser identificada pelo nome de uma espécie de borboleta, tendo, então, a pele marcada com um complexo desenho correspondente.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0013','Capitães da Areia','Jorge Amado',1937,280,'Verdadeiro romance de formação, o livro nos torna íntimos de suas pequenas criaturas, cada uma delas com suas carências e suas ambições: do líder Pedro Bala ao religioso Pirulito, do ressentido e cruel Sem-Pernas ao aprendiz de cafetão Gato, do sensato Professor ao rústico sertanejo Volta Seca. Com a força envolvente da sua prosa, Jorge Amado nos aproxima desses garotos e nos contagia com seu intenso desejo de liberdade.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0014','O Príncipe Cruel','Holly Black',2018,322,'Jude tinha apenas sete anos quando seus pais foram brutalmente assasinados e ela e as irmãs levadas para viver no traiçoeiro Reino das Fadas. Dez anos depois, tudo o que Jude quer é se encaixar, mesmo sendo uma garota mortal. Mas todos os feéricos parecem desprezar os humanos... Especialmente o príncipe Cardan, o mais jovem e mais perverso dos filhos do Grande Rei de Elfhame.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0015','O Senhor dos Anéis- A Sociedade do Anel','J.R.R. Tolkien',1954,576,'Numa cidadezinha indolente do Condado, um jovem hobbit é encarregado de uma imensa tarefa. Deve empreender uma perigosa viagem através da Terra-média até as Fendas da Perdição, e lá destruir o Anel do Poder - a única coisa que impede o domínio maléfico do Senhor do Escuro. A Sociedade do Anel é a primeira Temporada da grande obra de ficção fantástica de J. R. R. Tolkien, O Senhor dos Anéis.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0016','Drácula','Bram Stoker',1897,418,'Drácula, um clássico que ainda corre quente na veia de inúmeras gerações de leitores por todo o mundo e a mais celebrada narrativa de vampiros, continua a transcender fronteiras de tempo, espaço, história e memória.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0017','O Pequeno Príncipe','Antoine de Saint-Exupéry',1943,96,'O Pequeno Príncipe, escrito pelo francês Antoine de Saint-Exupéry, é uma obra atemporal que encanta leitores de todas as idades desde sua publicação, em 1943. A história narra a jornada de um garotinho com os “cabelos da cor do ouro” que vive no planeta B 612 e viaja pelo universo em busca de sabedoria e amizade. Com uma linguagem poética e delicada, Saint-Exupéry nos presenteia com uma narrativa rica em valores e que reforça a importância da simplicidade e do amor verdadeiro.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0018','O Menino do Pijama Listrado','John Boyne',2008,192,'Bruno tem nove anos e não sabe nada sobre o Holocausto e a Solução Final contra os judeus. Também não faz ideia que seu país está em guerra com boa Temporada da Europa, e muito menos que sua família está envolvida no conflito.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0019','Memórias Póstumas de Brás Cubas','Machado de Assis',1881,320,'Neste romance repleto de digressões filosóficas, o escritor se vale da posição privilegiada de Brás Cubas, que, como defunto autor, narra as suas desventuras e revela as contradições da sociedade brasileira do século XIX, por meio de uma análise aprofundada de seus personagens.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0020','Ai Meus Deuses','Tera Lynn Childs',2008,304,'A vida de Phoebe Castro vira do avesso quando sua mãe anuncia que irá se casar com um estranho misterioso. Para completar, as duas terão que se mudar para o outro lado do mundo: a Grécia! Phoebe terá que dizer adeus ao sonho de cursar a mesma universidade que suas melhores amigas. Como se tudo isso não bastasse, ela ainda terá que frequentar uma escola superexclusiva na qual seu padrasto é o diretor. E os alunos são tudo, menos comuns: são descendentes dos deuses gregos e com direito a superpoderes!');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0021','50 Ideias de Física Quântica que Você Precisa Conhecer','Joanne Baker',2015,216,'Em 50 ideias de Física Quântica a autora Joanne Baker explica de maneira acessível que a física quântica não é intuitiva o mundo subatômico se comporta de modo bem diferente do mundo clássico com o qual estamos familiarizados.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0022','50 Tons de Cinza','E. L. James',2012,480,'Quando Anastasia Steele entrevista o jovem empresário Christian Grey, descobre nele um homem atraente, brilhante e profundamente dominador. Ingênua e inocente, Ana se surpreende ao perceber que, a despeito da enigmática reserva de Grey, está desesperadamente atraída por ele. Incapaz de resistir à beleza discreta, à timidez e ao espírito independente de Ana, Grey admite que também a deseja ― mas em seus próprios termos.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0023','Moby Dick','Herman Melville',1851,656,'A história do capitão Ahab, em busca de vingança contra o terrível cachalote que amputara sua perna, entrou definitivamente para a cultura popular, inspirando, entre outras criações, pinturas de Jackson Pollock e Frank Stella, adaptações de Orson Welles para o rádio e o teatro, um filme de John Huston, e até um blues do Led Zeppelin.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0024','Não Conte a Ninguém','Harlan Coben',2001,238,'Enquanto comemoravam o aniversário de seu primeiro beijo, o Dr. David Beck e sua esposa, Elizabeth, sofreram um terrível ataque. Ele foi golpeado e caiu no lago, inconsciente. Ela foi raptada e brutalmente assassinada por um serial killer.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0025','Harry Potter e a Pedra Filosofal','J.K. Rowling',1997,208,'Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural. Pelo contrário. Até os 10 anos, Harry foi uma espécie de gata borralheira: maltratado pelos tios, herdava roupas velhas do primo gorducho, tinha óculos remendados e era tratado como um estorvo. No dia de seu aniversário de 11 anos, entretanto, ele parece deslizar por um buraco sem fundo, como o de Alice no país das maravilhas, que o conduz a um mundo mágico.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0026','As Crônicas de Nárnia','C.S. Lewis',1950,750,'Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal - o que mais um leitor poderia querer de um livro? O livro que tem tudo isso é ''O leão, a feiticeira e o guarda-roupa'', escrito em 1949 por Clive Staples Lewis. Mas Lewis não parou por aí. Seis outros livros vieram depois e, juntos, ficaram conhecidos como ''As crônicas de Nárnia''.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0027','Percy Jackson e Os Olimpianos- ladrão de raios','Rick Riordan',2015,331,'Unindo mitologia grega, muita aventura e tramas hilárias, a história de Rick Riordan sobre um adolescente com TDAH que descobre ser filho do deus do mar e precisa navegar entre o mundo humano e o divino.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0028','Morro dos Ventos Uivantes','Emily Brontë',1847,368,'Único romance da escritora inglesa Emily Brontë, O morro dos ventos uivantes retrata uma trágica história de amor e obsessão em que os personagens principais são a obstinada e geniosa Catherine Earnshaw e seu irmão adotivo, Heathcliff. Grosseiro, humilhado e rejeitado, ele guarda apenas rancor no coração, mas tem com Catherine um relacionamento marcado por amor e ódio.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0029','Orgulho e Preconceito','Jane Austen',1813,448,'Em Orgulho e Preconceito, Jane Austen nos apresenta os Bennets: uma família nobre, porém sem dinheiro, composta pelo pai, pela mãe e por cinco moças, todas em idade de se casar e nenhuma com direito a herdar a propriedade da família.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0030','Razão e Sensibilidade','Jane Austen',1811,400,'''Razão e Sensibilidade'' é um livro em que as irmãs Elinor e Marianne representam uma dualidade, de maneira alternada, ao longo da narrativa. As expectativas vividas pelas duas com a perda, o amor e a esperança, nos aponta para um excelente panorama da vida das mulheres de sua época.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0031','1984','George Orwell',1949,416,'Winston, herói de 1984, último romance de George Orwell, vive aprisionado na engrenagem totalitária de uma sociedade completamente dominada pelo Estado, onde tudo é feito coletivamente, mas cada qual vive sozinho. Ninguém escapa à vigilância do Grande Irmão, a mais famosa personificação literária de um poder cínico e cruel ao infinito, além de vazio de sentido histórico.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0032','Macunaíma','Mário de Andrade',1928,240,'As aventuras de Macunaíma, o anti-herói preguiçoso e sem caráter. Ele nasce negro no sertão, mas vira branco, vai para a cidade com os irmãos e se envolve com prostitutas, guerrilheiras e enfrenta todo tipo de gente em sua jornada.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0033','Grande Sertão Veredas','João Guimarães Rosa',1956,560,'Grande sertão: veredas é o livro mais famoso de Guimarães Rosa e conta a história de amor entre Riobaldo e Diadorim (ou Reinaldo). O ex-jagunço Riobaldo relata, para um interlocutor não nomeado na obra, fatos de sua juventude em meio a um bando de jagunços.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0034','Dom Casmurro','Machado de Assis',1899,208,'''Dom Casmurro'' conta a história de Bento Santiago (Bentinho), apelidado de Dom Casmurro por ser calado e introvertido. Na adolescência, apaixona-se por Capítu, abandonando o seminário e, com ele, os desígnios traçados por sua mãe, Dona Glória, para que se tornasse padre.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0035','O Cortiço','Aluísio Azevedo',1890,304,'O romance mostra as mazelas e a vida miserável dos moradores de duas habitações coletivas. João Romão é ganancioso comerciante de origem portuguesa, dono de um terreno no Rio de Janeiro onde constrói moradias de baixo custo para obter renda.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0036','Gabriela Cravo e Canela','Jorge Amado',1958,336,'O romance é ambientado na Ilhéus dos anos 1920, uma cidade do interior baiano que passa por súbitas transformações graças à riqueza que a cultura do cacau está trazendo para a região. Tudo começa quando a cidade está em ebulição com a notícia de um duplo assassinato.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0037','Vidas Secas','Graciliano Ramos',1938,176,'A história de uma família pobre da região seca do Nordeste e sua luta diária por trabalho e comida para sobreviver e superar as dificuldades do ambiente árido em que vive. Baseado no livro homônimo de Graciliano Ramos.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0038','A Moreninha','Joaquim Manuel de Macedo',1844,144,'Uma leve e divertida história de amor entre um jovem estudante e uma bela moreninha nos salões do Rio de Janeiro colonial.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0039','Iracema','José de Alencar',1865,192,'O romance conta o amor de um branco, Martim Soares Moreno, pela índia Iracema, a virgem dos lábios de mel. A relação do casal serviria de alegoria para a formação da nação brasileira.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0040','O Ateneu','Raul Pompeia',1888,147,'Nessa obra, o narrador-personagem Sérgio conta, em caráter memorialístico, a sua experiência como interno no Ateneu, um colégio onde estudam os filhos da rica burguesia carioca do século XIX. Nessa instituição, o menino de 11 anos vai aprender a viver em uma sociedade corrupta, onde sobrevivem os mais fortes.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0041','A Escrava Isaura','Bernardo Guimarães',1875,176,'Escrito em plena campanha abolicionista, o livro conta as desventuras de Isaura, a escrava branca, filha de Miguel, um branco ex-feitor da fazenda, e de uma escrava negra. A jovem, criada por sua senhora como se pertencesse à família, vê sua condição mudar completamente da noite para o dia.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0042','O Guarani','José de Alencar',1857,352,'A história do amor proibido entre o índio Peri e a jovem branca. O relacionamento se concretiza com o consentimento do pai da moça, graças ao ataque dos índios Aimorés à fortaleza de sua família. É quando o fidalgo pede a Peri que salve sua filha.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0043','A divina Comédia','Dante Alighieri',1472,696,'O livro relata a viagem de Dante ao Inferno, ao Purgatório e ao Paraíso.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0044','Dom Quixote','Miguel de Cervantes',1605,1033,'A história mostra um ingênuo senhor rural, cujo passatempo favorito é a leitura de livros de cavalaria. O senhor acaba acreditando literalmente nas aventuras escritas e, por isso, decide tornar-se um cavaleiro andante. Suas viagens sucedem-se sob a alucinação de que estava vivendo na era da cavalaria.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0045','Frankenstein','Mary Shelley',1818,240,'O brilhante e pouco ortodoxo doutor Victor Frankenstein trabalha na criação de um monstro com Temporadas de diferentes corpos humanos. Após ser rejeitada pelo criador, a criatura escapa e passa a agir com uma violenta sede de vingança.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0046','Os Três Mosqueteiros','Alexandre Dumas',1844,672,'Os três mosqueteiros, romance do escritor francês Alexandre Dumas, ambientado no século XVII, retrata de forma descontraída e divertida a vida francesa da época, com suas intrigas políticas e amorosas, com seus vilões e heróis, com sua nobreza e lacaios.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0047','Os Miseráveis','Victor Hugo',1862,1511,'“Os Miseráveis” conta a história de um homem que sofre durante toda sua vida por causa de um erro cometido na juventude. A saga de Jean Valjean se passa na França revolucionária do final do século XVIII e início do XIX quando monarquistas e republicanos lutavam pelas ruas.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0048','O Corvo','Edgar Allan Poe',1845,200,'O enredo versa sobre os delírios de um homem após a morte de sua amada, Lenora, e trata sobre a dor da perda, a falta de esperança e a angústia da existência.');
INSERT INTO livros (id,titulo,autor,ano,numero_paginas,descricao) VALUES ('L0049','Madame Bovary','Gustave Flaubert',1856,398,'Numa pacata cidadezinha da França do século 19, Emma Bovary é a bela esposa de Charles Bovary, um médico da região. As complicações na vida de Emma começam quando ela dá início a uma aventura extraconjugal com o objetivo de se promover na sociedade, melhorar sua posição social e deixar de viver à sombra do marido.');